name: CI ENVIROMENTS

on:
  push:
    branches: ["*"]

jobs:
  master:
    # if: false
    # if: ${{ false }}
    runs-on: ubuntu-latest
    # environment:
      # name: dev
      # url: 'https://meuguia.tv'
    steps:
      - name: RUN MASTER
        run: echo 'RUN MASTER'

        